### ISSUE TITLE
problem with getWindow().setExitTransition

### ISSUE THREAD

**Issue by rexi1r** [andkulikov/Transitions-Everywhere#21] opened 2015-05-08 14:06 UTC
hi.
method getWindow().setExitTransition just get android.transition.Explode as a parameter.
but i want to use this kind of transition in android api below 21.
how can i do that?

**Comment by andkulikov** [comment] 2015-05-08 19:54
sorry, activity and fragment transitions not backported for now. it's not so simple.
but you can imitate exitTransition by yourself. instead of calling finish() you can call beginDelayedTransition with explode transition as argument and remove all views from root view. and add listener to explode transition with  finish() in onTransitionEnd callback

**Comment by andkulikov** [comment] 2015-05-21 09:24
duplicate of https://github.com/andkulikov/Transitions-Everywhere/issues/11

**Closed by andkulikov** 2015-05-21 09:24 UTC

**Comment by raphaelbgr** [comment] 2018-01-25 17:57
Is it backported already? this post is from 2015, maybe it is nwo in 2018..

**Comment by andkulikov** [comment] 2018-01-25 23:41
No. Its imposible to backport them. If you want Fragment transitions you can try official support transitions library
